# Generated by Django 4.2.1 on 2023-05-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emlpoyess',
            new_name='Employees',
        ),
    ]
