# Generated by Django 4.2.1 on 2023-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(max_length=2)),
                ('duration', models.DurationField()),
                ('authorName', models.CharField(max_length=30)),
            ],
        ),
    ]
